### PR TITLE
Change queue driver

### PR DESCRIPTION
**Pull request by eluhr**
Use the `yii\queue\db\Queue` instead of `yii\queue\redis\Queue`. Before merging, the `dmstr/yii2-resque-module` package needs some updates as well as the dependency to `ignatenkovnikita/yii2-queuemanager` needs to be dropped.

### CODE REVIEW

**Comment by eluhr** [comment]
Removed dependency to `ignatenkovnikita/yii2-queuemanager` and upgraded `dmstr/yii2-resque-module` to version 3

**Comment by eluhr** [comment]
@schmunk42 When merged Tag & Release -> 5.10.2?

**Comment by eluhr** [comment]
The following changes have been made to the `dmstr/yii2-resque-module`: https://github.com/dmstr/yii2-resque-module/compare/2.0.0...3.0.0

**Review by schmunk42 — APPROVED** [review]

**Comment by schmunk42** [comment]
@eluhr  Should go into 5.11 I think.

**Pull request merged**
