### PR TITLE
Anonymous login page

### PR DESCRIPTION
**Pull request by eluhr**
New optional env *APP_LOGIN_URL* and login page /security/login

### CODE REVIEW

**Comment by eluhr** [comment]
Maybe we don't need the env at all and can do that via the config. Although this of course has the advantage that you can easily turn this on and off with the environment variable

**Comment by schmunk42** [comment]
Actually this should just be a view in `yii2-backend-module`, although a small derived controller might be necessary.

**Comment by eluhr** [comment]
Should I then move the whole thing to the backend module?

**Comment by schmunk42** [comment]
I think it's the best option.

CC: @handcode Other suggestions?

**Pull request closed without merging**
